from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.loginview, name='login'),
    url(r'^logout/$', views.logoutview, name='logout'),
    url(r'^quizpage1/(?P<value>\d+)/$', views.quizpage1, name='quizpage1'),
    url(r'^quizpage2/(?P<value>\d+)/$', views.quizpage2, name='quizpage2'),
    url(r'^quizpage3/(?P<value>\d+)/$', views.quizpage3, name='quizpage3'),
    url(r'^quizpage4/(?P<value>\d+)/$', views.quizpage4, name='quizpage4'),
    url(r'^quizpage5/(?P<value>\d+)/$', views.quizpage5, name='quizpage5'),
    url(r'^quizpage6/(?P<value>\d+)/$', views.quizpage6, name='quizpage6'),
    url(r'^quizpage7/(?P<value>\d+)/$', views.quizpage7, name='quizpage7'),
    url(r'^quizpage8/(?P<value>\d+)/$', views.quizpage8, name='quizpage8'),
    url(r'^quizpage9/(?P<value>\d+)/$', views.quizpage9, name='quizpage9'),
    url(r'^quizpage10/(?P<value>\d+)/$', views.quizpage10, name='quizpage10'),

    url(r'^quizpage11/(?P<value>\d+)/$', views.quizpage11, name='quizpage11'),
    url(r'^quizpage12/(?P<value>\d+)/$', views.quizpage12, name='quizpage12'),
    url(r'^quizpage13/(?P<value>\d+)/$', views.quizpage13, name='quizpage13'),
    url(r'^quizpage14/(?P<value>\d+)/$', views.quizpage14, name='quizpage14'),
    url(r'^quizpage15/(?P<value>\d+)/$', views.quizpage15, name='quizpage15'),
    url(r'^quizpage16/(?P<value>\d+)/$', views.quizpage16, name='quizpage16'),
    url(r'^quizpage17/(?P<value>\d+)/$', views.quizpage17, name='quizpage17'),
    url(r'^quizpage18/(?P<value>\d+)/$', views.quizpage18, name='quizpage18'),
    url(r'^quizpage19/(?P<value>\d+)/$', views.quizpage19, name='quizpage19'),
    url(r'^quizpage20/(?P<value>\d+)/$', views.quizpage20, name='quizpage20'),

    url(r'^quizpage21/(?P<value>\d+)/$', views.quizpage21, name='quizpage21'),
    url(r'^quizpage22/(?P<value>\d+)/$', views.quizpage22, name='quizpage22'),
    url(r'^quizpage23/(?P<value>\d+)/$', views.quizpage23, name='quizpage23'),
    url(r'^quizpage24/(?P<value>\d+)/$', views.quizpage24, name='quizpage24'),
    url(r'^quizpage25/(?P<value>\d+)/$', views.quizpage25, name='quizpage25'),
    url(r'^quizpage26/(?P<value>\d+)/$', views.quizpage26, name='quizpage26'),
    url(r'^quizpage27/(?P<value>\d+)/$', views.quizpage27, name='quizpage27'),
    url(r'^quizpage28/(?P<value>\d+)/$', views.quizpage28, name='quizpage28'),
    url(r'^quizpage29/(?P<value>\d+)/$', views.quizpage29, name='quizpage29'),
    url(r'^quizpage30/(?P<value>\d+)/$', views.quizpage30, name='quizpage30'),

    url(r'^quizpage31/(?P<value>\d+)/$', views.quizpage31, name='quizpage31'),
    url(r'^quizpage32/(?P<value>\d+)/$', views.quizpage32, name='quizpage32'),
    url(r'^quizpage33/(?P<value>\d+)/$', views.quizpage33, name='quizpage33'),
    url(r'^quizpage34/(?P<value>\d+)/$', views.quizpage34, name='quizpage34'),
    url(r'^quizpage35/(?P<value>\d+)/$', views.quizpage35, name='quizpage35'),
    url(r'^quizpage36/(?P<value>\d+)/$', views.quizpage36, name='quizpage36'),
    url(r'^quizpage37/(?P<value>\d+)/$', views.quizpage37, name='quizpage37'),
    url(r'^quizpage38/(?P<value>\d+)/$', views.quizpage38, name='quizpage38'),
    url(r'^quizpage39/(?P<value>\d+)/$', views.quizpage39, name='quizpage39'),
    url(r'^quizpage40/(?P<value>\d+)/$', views.quizpage40, name='quizpage40'),

    url(r'^quizpage41/(?P<value>\d+)/$', views.quizpage41, name='quizpage41'),
    url(r'^quizpage42/(?P<value>\d+)/$', views.quizpage42, name='quizpage42'),
    url(r'^quizpage43/(?P<value>\d+)/$', views.quizpage43, name='quizpage43'),
    url(r'^quizpage44/(?P<value>\d+)/$', views.quizpage44, name='quizpage44'),
    url(r'^quizpage45/(?P<value>\d+)/$', views.quizpage45, name='quizpage45'),
    url(r'^quizpage46/(?P<value>\d+)/$', views.quizpage46, name='quizpage46'),
    url(r'^quizpage47/(?P<value>\d+)/$', views.quizpage47, name='quizpage47'),
    url(r'^quizpage48/(?P<value>\d+)/$', views.quizpage48, name='quizpage48'),
    url(r'^quizpage49/(?P<value>\d+)/$', views.quizpage49, name='quizpage49'),
    url(r'^quizpage50/(?P<value>\d+)/$', views.quizpage50, name='quizpage50'),

    url(r'^quizpage51/(?P<value>\d+)/$', views.quizpage51, name='quizpage51'),
    url(r'^quizpage52/(?P<value>\d+)/$', views.quizpage52, name='quizpage52'),
    url(r'^quizpage53/(?P<value>\d+)/$', views.quizpage53, name='quizpage53'),
    url(r'^quizpage54/(?P<value>\d+)/$', views.quizpage54, name='quizpage54'),
    url(r'^quizpage55/(?P<value>\d+)/$', views.quizpage55, name='quizpage55'),
    url(r'^quizpage56/(?P<value>\d+)/$', views.quizpage56, name='quizpage56'),
    url(r'^quizpage57/(?P<value>\d+)/$', views.quizpage57, name='quizpage57'),
    url(r'^quizpage58/(?P<value>\d+)/$', views.quizpage58, name='quizpage58'),
    url(r'^quizpage59/(?P<value>\d+)/$', views.quizpage59, name='quizpage59'),
    url(r'^quizpage60/(?P<value>\d+)/$', views.quizpage60, name='quizpage60'),

    url(r'^results/$', views.results, name='results'),
    url(r'^percentile/$', views.percentile, name='percentile'),
    url(r'^generatepdf/$', views.generatepdf, name='generatepdf'),
    url(r'^back/$', views.back, name='back'),



]