# Generated by Django 2.1.7 on 2019-02-27 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('mobileNumber', models.CharField(max_length=12)),
                ('score', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0)),
                ('ch1', models.IntegerField(default=0)),
                ('ch2', models.IntegerField(default=0)),
                ('ch3', models.IntegerField(default=0)),
                ('ch4', models.IntegerField(default=0)),
                ('ch5', models.IntegerField(default=0)),
                ('ch6', models.IntegerField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
