# Generated by Django 2.1.7 on 2019-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizduration',
            field=models.IntegerField(default=0),
        ),
    ]
