# Generated by Django 2.1.7 on 2019-02-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190227_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quizduration',
        ),
    ]
