# Generated by Django 2.1.7 on 2019-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_quizduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ch10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ch7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ch8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ch9',
            field=models.IntegerField(default=0),
        ),
    ]
