# Generated by Django 2.1.7 on 2019-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190415_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tvashid',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
