# Generated by Django 2.1.7 on 2019-05-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userprofile_tvashid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tvashid',
            new_name='TvashId',
        ),
    ]
